name: dart_bitcoin_ops
description: Bitcoin OP Codes
version: 1.0.0
homepage: https://github.com/dart-bitcoin-lib/dart-bitcoin-ops
repository: https://github.com/dart-bitcoin-lib/dart-bitcoin-ops

environment:
  sdk: '>=2.12.0 <3.0.0'